### ISSUE TITLE
OTP version supported?

### ISSUE THREAD

**Issue by lpgauth** [rabbitmq/looking-glass#1]
Hi Loic,
Readme says OTP-19 and up should be supported but it looks like you need at least OTP-20?

https://github.com/erlang/otp/pull/1346

```erlang
compile: warnings being treated as errors
src/lg_socket_client.erl:16: undefined callback function code_change/4 (behaviour 'gen_statem')
make[1]: *** [ebin/looking_glass.app] Error 1
```

**Comment by michaelklishin** [comment]
@lpgauth you can disable that particular warning or fix it, then it should compile on OTP 19 ;)

**Comment by michaelklishin** [comment]
I'm surprised you are getting it on OTP 19, it's usually OTP 20 upgrades that run into that warning.

**Comment by lpgauth** [comment]
@michaelklishin yup https://github.com/rabbitmq/looking-glass/pull/2
