### ISSUE TITLE
compiled successfully but failed to start

### ISSUE THREAD

**Issue by gy8409** [rabbitmq/looking-glass#11]
OS: Ubuntu 18.04 LTS
Erl: Erlang/OTP 20 [erts-9.3.3.13]

(relay01@node1)1> application:ensure_all_started(looking_glass).
{error,{lz4,{"no such file or directory","lz4.app"}}}

**Comment by essen** [comment]
Please provide the compile log.

**Comment by michaelklishin** [comment]
One reason can be that you don't have `lz4` (the native library) installed.

**Comment by gy8409** [comment]
[compile.log](https://github.com/rabbitmq/looking_glass/files/4311538/compile.log)

@essen

**Comment by essen** [comment]
It's a Make/Rebar incompatibility issue. In particular `lz4` is downloaded and built in the wrong `deps` directory, and Rebar probably doesn't even know about it. Exact issue is either the `rebar.config` or Erlang.mk or both.

**Comment by gy8409** [comment]
Is there any work round to let me try looking glass？

Actually I got more errors when compile on Mac OS.

**Comment by essen** [comment]
Should work if you depend on https://github.com/rabbitmq/lz4-erlang directly before Looking Glass itself.

**Comment by gy8409** [comment]
> Should work if you depend on https://github.com/rabbitmq/lz4-erlang directly before Looking Glass itself.

Failed to compile lz4-erlang.
I created an issue in https://github.com/rabbitmq/lz4-erlang/issues/7

**Comment by gy8409** [comment]
After I compiled successfully and get application looking glass to run, I got the following errors when I stop lg trace:

> {undef,[{logger,debug,["~s: Trying to load \"~s\" from \"~s\"",[lz4,"lz4_nif","/home/gy/relay/_build/default/lib/lz4/priv/x86_64-unknown-linux-gnu"]],[]},{lz4_nif,'-on_load/0-fun-0-',2,[{file,"/home/gy/relay/_build/default/lib/lz4/src/lz4_nif.erl"},{line,32}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{code_server,'-handle_on_load/5-fun-0-',1,[{file,"code_server.erl"},{line,1340}]}]}

**Comment by gy8409** [comment]
Can I just print the lg trace into a non-compression file and profile the result?

**Comment by michaelklishin** [comment]
`logger` is the new OTP logger available as of OTP 22 IIRC. We don't target older Erlang versions.

**Comment by essen** [comment]
OTP 21+. The README needs to be updated.

**Comment by gy8409** [comment]
We can't upgrade to a higher version easily, maybe I should just give up integrating looking glass unfortunately.

**Comment by michaelklishin** [comment]
There are several other profilers available for Erlang. `fprof` is what we originally used but it produces such enormous output files that it is not realistic to use it to profile RabbitMQ in 12-24 hour long sessions.

We have no intention to support OTP < 21 since [supported RabbitMQ versions require 21.3](https://www.rabbitmq.com/which-erlang.html).

**Comment by michaelklishin** [comment]
@essen if there's anything else for us to address here please file a separate issue as this belongs in Discussions IMO.
