### ISSUE TITLE
Fix rebar.config

### ISSUE THREAD

**Issue by essen** [rabbitmq/looking-glass#12]
The rebar.config currently compiles but not in the way Rebar expects. In particular the paths are wrong. See https://github.com/rabbitmq/looking_glass/issues/11 for more details.

**Comment by lhoguin** [comment]
A fix has been merged that will work well enough until I have time to figure out why Rebar3 doesn't cooperate with Erlang.mk (REBAR_DEPS_DIR not set anymore?).
